In [1]:
import os, json
import pandas as pd
import matplotlib.pyplot as plt

In [43]:
%matplotlib inline

In [2]:
full_order_book_header = ['date', 'message', 'security',
                         'trade_ID', 'order_ID', 'price',
                         'quantily', 'trade_type', 'trade_time',
                          'side', 'order_type', 'order_book_position',
                         'aggregated_number_of_shares', 'cooling_start',
                         'cooling_end', 'VCM', 'VCM_lower', 
                         'VCM_upper', 'reference_price', 'lower_price', 
                         'upper_price', 'order_imbalance_direction',
                         ]

In [22]:
full_book_csv_name = []
num = 30
for i in range(0,9):
    name = 'MC' + str(num + i)
    full_book_csv_name.append(name)

In [24]:
with open('full_book_csv_name.json', 'w') as outfile:
    json.dump(full_book_csv_name,outfile)

In [25]:
with open('column_name.json', 'w') as outfile:
    json.dump(full_order_book_header,outfile)

In [3]:
dt = pd.read_csv('./data/MC30_AllFB_20180201.csv', names=full_order_book_header, index_col=False)
dt['date'] = pd.to_datetime(dt['date'], format='%Y%m%d%H%M%S%f')
dt['trade_time'] =  pd.to_datetime(dt["trade_time"].apply(lambda x: format(x, 'f')), format='%Y%m%d%H%M%S%f.000000')
dt.set_index('date', inplace=True)

/home/david/anaconda3/envs/stock_option/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [ ]:
dt.head()

In [11]:
lunch_hour_list = list(dt.between_time('12:00','13:00').index)

In [12]:
dt_clean = dt.drop(lunch_hour_list)

In [14]:
dt_trade_hour = dt_clean.between_time('09:30','16:00')
dt_trade_hour.tail()

,message,security,trade_ID,order_ID,price,quantily,trade_type,trade_time,side,order_type,...,aggregated_number_of_shares,cooling_start,cooling_end,VCM,VCM_lower,VCM_upper,reference_price,lower_price,upper_price,order_imbalance_direction
date,,,,,,,,,,,,,,,,,,,,,
2018-02-01 15:59:59.992,30,68216,NaN,62829473.0,0.33,2000000.0,NaN,NaT,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:59.992,32,13664,NaN,62829105.0,NaN,NaN,NaN,NaT,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:59.992,30,13664,NaN,62829489.0,0.81,100000.0,NaN,NaT,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:59.992,32,13664,NaN,62829121.0,NaN,NaN,NaN,NaT,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:59.992,30,13664,NaN,62829505.0,0.81,100000.0,NaN,NaT,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
dt_stock_list = set(dt_trade_hour['security'].tolist())
target_stock = [5,939,1398,700,388,2318,2628,175,16,27]
stock_list = []
for stock in target_stock:
    if stock in dt_stock_list:
        stock_list.append(stock)

print (stock_list)

[939, 27]

In [15]:
dt_trade_hour[dt_trade_hour['security'] == 939]

,message,security,trade_ID,order_ID,price,quantily,trade_type,trade_time,side,order_type,...,aggregated_number_of_shares,cooling_start,cooling_end,VCM,VCM_lower,VCM_upper,reference_price,lower_price,upper_price,order_imbalance_direction
date,,,,,,,,,,,,,,,,,,,,,
2018-02-01 09:30:00.038,30,939,NaN,365521.0,9.31,2000.0,NaN,NaT,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.042,30,939,NaN,365729.0,9.12,3000.0,NaN,NaT,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.042,30,939,NaN,365745.0,9.13,1000.0,NaN,NaT,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.048,30,939,NaN,366321.0,9.10,9000.0,NaN,NaT,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.048,30,939,NaN,366337.0,9.06,7000.0,NaN,NaT,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.048,30,939,NaN,366353.0,9.11,5000.0,NaN,NaT,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.048,30,939,NaN,366369.0,9.08,1000.0,NaN,NaT,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.048,30,939,NaN,366481.0,9.11,419000.0,NaN,NaT,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.048,50,939,262.0,NaN,9.11,270000.0,0.0,2018-02-01 09:30:00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.048,32,939,NaN,351665.0,NaN,NaN,NaN,NaT,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.048,31,939,NaN,366481.0,NaN,149000.0,NaN,NaT,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.048,50,939,263.0,NaN,9.11,4000.0,0.0,2018-02-01 09:30:00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.048,32,939,NaN,358225.0,NaN,NaN,NaN,NaT,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.048,31,939,NaN,366481.0,NaN,145000.0,NaN,NaT,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.048,50,939,264.0,NaN,9.11,145000.0,0.0,2018-02-01 09:30:00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.048,32,939,NaN,358545.0,NaN,NaN,NaN,NaT,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.048,32,939,NaN,366481.0,NaN,NaN,NaN,NaT,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.048,30,939,NaN,366497.0,9.11,400000.0,NaN,NaT,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.048,50,939,265.0,NaN,9.11,5000.0,0.0,2018-02-01 09:30:00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.048,32,939,NaN,366353.0,NaN,NaN,NaN,NaT,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.048,31,939,NaN,366497.0,NaN,395000.0,NaN,NaT,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.057,32,939,NaN,249441.0,NaN,NaN,NaN,NaT,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.060,30,939,NaN,366977.0,9.11,37000.0,NaN,NaT,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.060,30,939,NaN,366993.0,9.12,37000.0,NaN,NaT,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.060,30,939,NaN,367009.0,9.13,37000.0,NaN,NaT,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.061,30,939,NaN,367057.0,9.14,39000.0,NaN,NaT,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.061,30,939,NaN,367073.0,9.15,75000.0,NaN,NaT,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.061,30,939,NaN,367089.0,9.16,37000.0,NaN,NaT,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.074,30,939,NaN,367569.0,9.30,10000.0,NaN,NaT,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 09:30:00.075,30,939,NaN,367649.0,9.04,3000.0,NaN,NaT,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-02-01 15:59:55.277,32,939,NaN,62813665.0,NaN,NaN,NaN,NaT,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:55.280,30,939,NaN,62813713.0,8.95,1000.0,NaN,NaT,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:56.296,30,939,NaN,62817729.0,8.88,5000.0,NaN,NaT,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:56.637,30,939,NaN,62818481.0,8.95,1000.0,NaN,NaT,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:56.637,50,939,27688.0,NaN,8.95,1000.0,0.0,2018-02-01 15:59:56,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:56.637,32,939,NaN,62818481.0,NaN,NaN,NaN,NaT,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:56.637,31,939,NaN,62318673.0,NaN,47000.0,NaN,NaT,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:56.645,32,939,NaN,60801025.0,NaN,NaN,NaN,NaT,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:56.645,30,939,NaN,62818497.0,8.97,94000.0,NaN,NaT,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:56.976,30,939,NaN,62819281.0,8.95,3000.0,NaN,NaT,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:57.204,32,939,NaN,62813105.0,NaN,NaN,NaN,NaT,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:57.229,30,939,NaN,62820161.0,8.96,200000.0,NaN,NaT,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:57.449,30,939,NaN,62820881.0,8.94,500000.0,NaN,NaT,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:57.450,30,939,NaN,62820897.0,8.93,500000.0,NaN,NaT,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:57.659,32,939,NaN,54434193.0,NaN,NaN,NaN,NaT,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:57.711,32,939,NaN,54444385.0,NaN,NaN,NaN,NaT,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:57.762,32,939,NaN,54453729.0,NaN,NaN,NaN,NaT,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:57.862,32,939,NaN,62797361.0,NaN,NaN,NaN,NaT,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:57.862,30,939,NaN,62822833.0,8.94,20000.0,NaN,NaT,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:57.890,32,939,NaN,62702193.0,NaN,NaN,NaN,NaT,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:58.122,32,939,NaN,62489025.0,NaN,NaN,NaN,NaT,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:58.123,31,939,NaN,62805217.0,NaN,15000.0,NaN,NaT,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:58.136,32,939,NaN,62434113.0,NaN,NaN,NaN,NaT,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:58.136,30,939,NaN,62823361.0,8.94,71000.0,NaN,NaT,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:58.604,32,939,NaN,62346497.0,NaN,NaN,NaN,NaT,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:59.466,30,939,NaN,62827761.0,8.88,1000.0,NaN,NaT,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:59.791,32,939,NaN,42422737.0,NaN,NaN,NaN,NaT,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:59.793,32,939,NaN,42423697.0,NaN,NaN,NaN,NaT,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:59.793,32,939,NaN,42423825.0,NaN,NaN,NaN,NaT,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-02-01 15:59:59.972,32,939,NaN,62813617.0,NaN,NaN,NaN,NaT,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
ccb = dt_trade_hour[(dt_trade_hour["trade_time"].notnull()) & (dt_trade_hour['security'] == 939)][['price','quantily','side']]

In [19]:
ccb.head()

                         price  quantily  side
date
2018-02-01 09:30:00.048   9.11  270000.0   NaN
2018-02-01 09:30:00.048   9.11    4000.0   NaN
2018-02-01 09:30:00.048   9.11  145000.0   NaN
2018-02-01 09:30:00.048   9.11    5000.0   NaN
2018-02-01 09:30:00.101   9.11  395000.0   NaN

In [20]:
ccb.between_time('12:00','13:00')

Empty DataFrame
Columns: [price, quantily, side]
Index: []